#!/usr/bin/env ruby

# You might want to change this
ENV["RAILS_ENV"] ||= "production"

require File.dirname(__FILE__) + "/../../config/application"
Rails.application.require_environment!

# Set the temporary directory for saving xls / xlsx files
ENV["ROO_TMP"] ||= "#{Rails.root}/tmp".to_s

$running = true
Signal.trap("TERM") do 
  $running = false
end

while($running) do
  if ImportJob.has_next
    process_lock = ProcessLock.acquire_lock('Geotidy_ImportJob', Process.pid)
    if process_lock.locked?
      ImportJob.process_next
      process_lock.unlock!
    end
  end  
  # checks every 2 minutes
  sleep 2 * 60
end